### ISSUE TITLE
OrthoFinder failed (GalaxyDev)

### ISSUE THREAD

**Issue by alimatai** [abims-sbr/adaptsearch_old#28]
Suite à un crash d'orthofinder signalé par Didier :

OrthoFinder a crashé sous GalaxyDev, en utilisant les outputs de TransDecoder. 
Le message d'erreur est : `mv: cannot stat Results_*: No such file or directory`
Il s'agit de la commande qui renomme le dossier de résultats créée par OrthoFinder, la première commande bash lancée après le run d'OrthoFinder.

- J'ai pu constater que la version de TransDecoder est plus récente que celle que j'ai utilisée lors de mes tests et benchmarks

- Je n'ai aucun problème en utilisant OrthoFinder en ligne de commande avec les fichiers qui posent problème sous Galaxy.

- Le bug ne se produit pas toujours, c'est selon les fichiers d'inputs utilisés (pas encore tiré ça au clair)

----------------------------------------------------------------------------------------------------------------------------------

Obtenu un autre message d'erreur en utilisant trois petits jeux de données test (outputs velvet de Filter_Assemblies passés dans TransDecoder puis OrthoFinder). Obtenu en utilisant la sélection multiple de fichiers d'input (en utilisant un dataset collection, c'est l'erreur de Didier qui a lieu ...) : 

```
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies3] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies1] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies3] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies1] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies3] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies1] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies3] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies1] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Warning: [blastp] Query is Empty!
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies3] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
BLAST Database error: No alias or index file found for protein database [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working/Results_Nov02/WorkingDirectory/BlastDBSpecies1] in search path [/w/galaxy/galaxydev/galaxy/database/jobs_directory/002/2430/working:/db/blast/all:]
Traceback (most recent call last):
  File "/w/conda/galaxydev/_conda/envs/__orthofinder@1.1.4/bin/orthofinder", line 1374, in 
    clustersFilename_pairs, statsFile, summaryText, orthogroupsResultsFilesString = DoOrthogroups(options, dirs, seqsInfo)    
  File "/w/conda/galaxydev/_conda/envs/__orthofinder@1.1.4/bin/orthofinder", line 1092, in DoOrthogroups
    Lengths = GetSequenceLengths(seqsInfo, fileInfo)
  File "/w/conda/galaxydev/_conda/envs/__orthofinder@1.1.4/bin/orthofinder", line 332, in GetSequenceLengths
    sequenceLengths[iSpecies][iCurrentSequence] = currentSequenceLength
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by alimatai** [comment]
Origine du bug de Didier : les outputs de TransDecoder n'ont pas l'extension "fasta". Or OrthoFInder se base sur l'extension des fichiers pour détecter ses inputs.
